name: weather_app
description: A Weather app built using Flutter.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  weekdays:
    path: packages/weekdays
  weather_api:
    path: packages/weather_api
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  weather: ^2.0.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
